# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.parsed_fileds import ParsedFileds 
from swagger_server.models.base_model_ import Model
from swagger_server import util


class Parsed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, fileds: List[ParsedFileds]=None):  # noqa: E501
        """Parsed - a model defined in Swagger

        :param fileds: The fileds of this Parsed.  # noqa: E501
        :type fileds: List[ParsedFileds]
        """
        self.swagger_types = {
            'fileds': List[ParsedFileds]
        }

        self.attribute_map = {
            'fileds': 'fileds'
        }

        self._fileds = fileds

    @classmethod
    def from_dict(cls, dikt) -> 'Parsed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Parsed of this Parsed.  # noqa: E501
        :rtype: Parsed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fileds(self) -> List[ParsedFileds]:
        """Gets the fileds of this Parsed.


        :return: The fileds of this Parsed.
        :rtype: List[ParsedFileds]
        """
        return self._fileds

    @fileds.setter
    def fileds(self, fileds: List[ParsedFileds]):
        """Sets the fileds of this Parsed.


        :param fileds: The fileds of this Parsed.
        :type fileds: List[ParsedFileds]
        """

        self._fileds = fileds
