# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParsedFileds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, data: object=None):  # noqa: E501
        """ParsedFileds - a model defined in Swagger

        :param type: The type of this ParsedFileds.  # noqa: E501
        :type type: str
        :param data: The data of this ParsedFileds.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'type': str,
            'data': object
        }

        self.attribute_map = {
            'type': '_type',
            'data': 'data'
        }

        self._type = type
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ParsedFileds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Parsed_fileds of this ParsedFileds.  # noqa: E501
        :rtype: ParsedFileds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ParsedFileds.


        :return: The type of this ParsedFileds.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ParsedFileds.


        :param type: The type of this ParsedFileds.
        :type type: str
        """

        self._type = type

    @property
    def data(self) -> object:
        """Gets the data of this ParsedFileds.


        :return: The data of this ParsedFileds.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this ParsedFileds.


        :param data: The data of this ParsedFileds.
        :type data: object
        """

        self._data = data
